/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author CarlosCastillo97
 */
public class FrmVerificarDPI extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmVerificarDPI
     */
    public FrmVerificarDPI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelTitulo = new javax.swing.JLabel();
        JTxtNumDPI = new javax.swing.JTextField();
        JBtnVerificar = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Verificar DPI");
        setToolTipText("");

        JLabelTitulo.setText("Número de DPI");

        JBtnVerificar.setText("Verificar");
        JBtnVerificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JBtnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnVerificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JBtnVerificar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JLabelTitulo)
                        .addComponent(JTxtNumDPI, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(JLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTxtNumDPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBtnVerificar)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnVerificarActionPerformed

     try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/RENAP", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from Persona where Num_DPI = ?");
            pst.setString(1, JTxtNumDPI.getText().trim());
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                JOptionPane.showMessageDialog(null,"El DPI es Correcto");
                String RENAP_Nomb="", RENAP_ApeP="", RENAP_ApeM="", RENAP_DPI="";
                RENAP_Nomb = (rs.getString("Nombres_Persona"));
                RENAP_ApeP = (rs.getString("Apellido_Paterno"));
                RENAP_ApeM = (rs.getString("Apellido_Materno"));
                RENAP_DPI = (rs.getString("Num_DPI"));
                
            } else {
                JOptionPane.showMessageDialog(null, "Usuario no registrado.");
              
            }
            
        }catch (Exception e){
            
        }
    }//GEN-LAST:event_JBtnVerificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnVerificar;
    private javax.swing.JLabel JLabelTitulo;
    private javax.swing.JTextField JTxtNumDPI;
    // End of variables declaration//GEN-END:variables
}
